version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  web:
    build: .
    command: bash -c “rm -f tmp/pids/server.pid && bin/dev”
    volumes:
      - .:/english_diary_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
